[package]
namespace   = "mcpplibs"
name        = "cmdline"
version     = "0.0.2"
description = "A simple command-line parsing library/framework for modern C++"
license     = "Apache-2.0"
authors     = ["mcpplibs"]
repo        = "https://github.com/mcpplibs/cmdline"

[targets.cmdline]
kind = "lib"

[dev-dependencies.compat]
gtest = "1.15.2"
